//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAPHANG
    {
        public int MaSach { get; set; }
        public string MaPhieuNhapHang { get; set; }
        public Nullable<int> Sluong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
        public virtual THONGTINSACH THONGTINSACH { get; set; }
    }
}
