//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.PHIEUDATHANGs = new HashSet<PHIEUDATHANG>();
        }

        [Key]
        public int MaKH { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Không được để trống tên")]
        [Display(Name = "Tên khách hàng")]
        public string TenKH { get; set; }

        [StringLength(250)]
        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string DiaChi { get; set; }

        [StringLength(50)]
        [Display(Name = "SDT")]
        [Required(ErrorMessage = "SĐT sai mặc định!!")]
        [RegularExpression(@"^((0(\d){9})|(086(\d){7})|(088(\d){7})|(089(\d){7})|(01(\d){9}))$",
                 ErrorMessage = "SDT phai du 10 số và đúng mặc định")]
        public string SDT { get; set; }


        [StringLength(50)]
        [Required(ErrorMessage = "Email không được để trống")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddThh:mm:ss}")]
        [Display(Name = "Ngày Sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }


        public string GioiTinh { get; set; }

        public Nullable<System.DateTime> NgayTao { get; set; }

        [Required(ErrorMessage = "Tài khoản không được để trống")]
        [StringLength(50)]
        [Display(Name = "Tài khoản")]
        public string TenDN { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [StringLength(50)]
        [Display(Name = "Mật khẩu")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATHANG> PHIEUDATHANGs { get; set; }
    }
}
