//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LIENHE
    {
        public int MaLH { get; set; }
        [StringLength(50)]
        [Display(Name = "Họ")]
        [Required(ErrorMessage = "Họ không được để trống")]
        public string Ho
        {
            get;
            set;
        }
        [StringLength(50)]
        [Display(Name = "Tên")]
        [Required(ErrorMessage = "Tên không được để trống")]
        public string Ten { get; set; }

        [StringLength(100)]
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email không được để trống")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [StringLength(50)]
        [Display(Name = "Điện thoại")]
        [Required(ErrorMessage = "Không được để trống số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        public string DienThoai { get; set; }

        [StringLength(500)]
        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "Nội dung cần nhập của bạn")]
        public string NoiDung { get; set; }


        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
