//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class PHIEUDATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATHANG()
        {
            this.CT_PHIEUDATHANG = new HashSet<CT_PHIEUDATHANG>();
        }
    
       [Key]
        [Display(Name = "Mã đơn hàng")]
        public int MaPhieuDH { get; set; }


        public Nullable<int> MaKH { get; set; }

        [Column(TypeName = "smalldatetime")]
        [Display(Name = "Ngày đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }


        public Nullable<int> Tong_SL_Dat { get; set; }

        public Nullable<double> ThanhTien { get; set; }

        [Display(Name = "Tình trạng")]
        public bool TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDATHANG> CT_PHIEUDATHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
