//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class PHIEUNHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAPHANG()
        {
            this.CT_PHIEUNHAPHANG = new HashSet<CT_PHIEUNHAPHANG>();
        }
        [StringLength(50)]
        [Display(Name = "Ma Phieu Nhap Hang")]
        [Required(ErrorMessage = "Không được để trống")]
        public string MaPhieuNhapHang { get; set; }
        [StringLength(50)]
        [Display(Name = "Ma NCC")]
        [Required(ErrorMessage = "Không được để trống")]
        public string MaNCC { get; set; }

        [Display(Name = "Ma NV")]
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<int> MaNV { get; set; }

        [Column(TypeName = "smalldatetime")]
        [Display(Name = "Ngày lập hóa đơn")]
        public Nullable<System.DateTime> NgayLap_PN { get; set; }

        //[Required(ErrorMessage = "Không được để trống")]
        public Nullable<int> TongSL { get; set; }

        //[Required(ErrorMessage = "Không được để trống")]
        public Nullable<double> TongTien_NH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPHANG> CT_PHIEUNHAPHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
