//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_MonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class THONGTINSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINSACH()
        {
            this.CT_PHIEUDATHANG = new HashSet<CT_PHIEUDATHANG>();
            this.CT_PHIEUNHAPHANG = new HashSet<CT_PHIEUNHAPHANG>();
        }

        [Key]
        [Display(Name = "Mã sách")]
        public int MaSach { get; set; }

        [Display(Name = "Mã loại")]
        [Required(ErrorMessage = "Vui lòng chọn thể loại")]
        public Nullable<int> MaLoai { get; set; }

        [Display(Name = "Mã tác giả")]
        [Required(ErrorMessage = "Vui lòng chọn tác giả")]
        public Nullable<int> MaTG { get; set; }

        [Display(Name = "Mã NXB")]
        [Required(ErrorMessage = "Vui lòng chọn nhà xuất bản")]
        public Nullable<int> MaNXB { get; set; }

        [StringLength(250)]
        [Display(Name = "Tên sách")]
        [Required(ErrorMessage = "Vui lòng nhập tên sách")]
        public string TenSach { get; set; }


        [Column(TypeName = "money")]
        [Display(Name = "Giá bán")]
        public Nullable<double> GiaSach { get; set; }

        [StringLength(500)]
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }

        [StringLength(50)]
        [Display(Name = "Ảnh bìa")]
        public string HinhAnh { get; set; }

        [Column(TypeName = "money")]
        [Display(Name = "Giá giảm")]
        public Nullable<double> GiamGia { get; set; }

        [Display(Name = "Số lượng tồn")]
        public Nullable<int> SLTon { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDATHANG> CT_PHIEUDATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPHANG> CT_PHIEUNHAPHANG { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
